name: Hello World on Develop Push and PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  say-hello:
    name: Print 'Hello World!'
    runs-on: ubuntu-latest

    steps:
      - name: Print greeting
        run: echo "Hello World!"